/* automatically generated by rust-bindgen */

extern "C" {
    pub fn cudaGLGetDevices(
        pCudaDeviceCount: *mut ::std::os::raw::c_uint,
        pCudaDevices: *mut ::std::os::raw::c_int,
        cudaDeviceCount: ::std::os::raw::c_uint,
        deviceList: cudaGLDeviceList,
    ) -> cudaError_t;
}
extern "C" {
    pub fn cudaGraphicsGLRegisterImage(
        resource: *mut *mut cudaGraphicsResource,
        image: GLuint,
        target: GLenum,
        flags: ::std::os::raw::c_uint,
    ) -> cudaError_t;
}
extern "C" {
    pub fn cudaGraphicsGLRegisterBuffer(
        resource: *mut *mut cudaGraphicsResource,
        buffer: GLuint,
        flags: ::std::os::raw::c_uint,
    ) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLSetGLDevice(device: ::std::os::raw::c_int) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLRegisterBufferObject(bufObj: GLuint) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLMapBufferObject(
        devPtr: *mut *mut ::std::os::raw::c_void,
        bufObj: GLuint,
    ) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLUnmapBufferObject(bufObj: GLuint) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLUnregisterBufferObject(bufObj: GLuint) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLSetBufferObjectMapFlags(
        bufObj: GLuint,
        flags: ::std::os::raw::c_uint,
    ) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLMapBufferObjectAsync(
        devPtr: *mut *mut ::std::os::raw::c_void,
        bufObj: GLuint,
        stream: cudaStream_t,
    ) -> cudaError_t;
}
extern "C" {
    pub fn cudaGLUnmapBufferObjectAsync(bufObj: GLuint, stream: cudaStream_t) -> cudaError_t;
}
